#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
mypath=$(readlink -f "${ZDOTDIR:-$HOME}/.zshrc")
prezto_home=${mypath:h:h}

source "${prezto_home}/init.zsh"



#aliases
source ~/.aliases

function setpwd() {
    set-window-title `pwd`
}

source ~/.path


